name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia in master se il tuo branch principale si chiama master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Application
        run: npx ng build --configuration production --base-href /gs1-italy-web-vocabulary-viewer/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/demo 
          branch: gh-pages 
