name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js (v24)
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Application
        
        run: npx ng build --configuration production --base-href /gs1-italy-web-vocabulary-viewer/

      - name: Verify Build Output Directory
        # Questo comando ci serve per capire nel log l'esatto nome della cartella generata dentro dist
        run: ls -R dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
